### PR TITLE
Revert dependency update

### PR DESCRIPTION
**Pull request by nprindle**
Somehow, updating the dependencies causes a strange bug where saving and quitting fills the world with Lander tiles. Even stranger, this only happens after minification, under the ci-specific dependencies. This reverts the dependency update and only updates `@nprindle/minewt`, instead.

I'll do more research to find what actually caused this bug.

### CODE REVIEW

**Comment by nprindle** [comment]
This may fail on Windows machines, so I'll take another look. This is probably an older bug with the minification that passed unnoticed until now, but I'll try to fix this too.

**Comment by nprindle** [comment]
On my Windows machine, `npm ci` fails because it, get this: can't find a Visual Studio installation.

I'm getting _really_ frustrated with `node-gyp` right about now.

**Comment by nprindle** [comment]
Wontfix. It works on Linux. The CI is on Linux. Good enough for me.

`node-gyp` bad.

**Comment by nprindle** [comment]
Actual reason has been found: `.constructor.name` is not a safe operation under closure renaming operations, but for some reason, this only happens when we move to Typescript `3.9.3`. The only major difference is that many things that used to be classes in the output become IIFEs returning classes. Fixing the root cause would entail quite a bit of restructuring, though.

**Comment by GRarer** [comment]
That is extremely weird. Not being able to use a newer version of tsc is unfortunate but not too much of an issue since this project is (hopefully) now finished, so this is an acceptable fix for now.

**Pull request merged**
