### PR TITLE
Styles/world screen

### PR DESCRIPTION
**Pull request by MGPAlpha**
Made sidebars scroll and made the canvas resize better on the world screen

### CODE REVIEW

**Comment by GRarer** [comment]
The scrollbars work correctly but the map does not scale correctly on my screen (2560x1440).

mapscaling

**Comment by MGPAlpha** [comment]
> The scrollbars work correctly but the map does not scale correctly on my screen (2560x1440).
> 
> mapscaling

Ok I can try to do something about that

**Comment by GRarer** [comment]
Can we do something about the black space between the map and the tile sidebar?

scaling2

The sidebar should be able to expand horizontally into that space if it's available, so that e.g. "adjacent to a habitat dome" would not be split over two lines if the screen has enough space for it to be on one.

**Comment by GRarer** [comment]
this causes a bug where the map moves left and right depending on how much width the sidebar takes up, which causes it to jarringly oscillate when clicking on different tile types.

stretch 1

stretch 2

This is a result of trying to get rid of the small black bar beneath the world map, right? I'm not sure that that small visual improvement is worth the added complications and edge cases. I'd recommend closing this PR and sending one that just adds the sidebar scroll bars.

**Comment by MGPAlpha** [comment]
ok

**Pull request closed without merging**
